
name: Deploy Jekyll Site from Private Repo

on:
  push:
    branches: ["main"] # 監控 main 分支的變更
    
  workflow_dispatch: # 支援手動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 檢出 Public Repository
    - name: Checkout Public Repository
      uses: actions/checkout@v3

    # 2. 檢出 Private Repository (SingleFile-Archives)
    - name: Checkout Private Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.MY_PRIVATE_REPOSITORY }}
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Private Token
        path: singlefile-repo # 提取到此資料夾

    # 3. 創建 singlefile-repo 目錄（如果不存在），然後從 Public Repo 複製必要檔案
    - name: Copy index_sample, *.css, *.sh to singlefile-repo
      run: |
        # 確保 singlefile-repo 目錄存在，並將檔案拷貝到 singlefile-repo 目錄
        mkdir -p singlefile-repo
        cp index_sample *.css *.sh singlefile-repo/
    
    # 4. 設置 Ruby 環境 (Jekyll 需要)
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
        
    # 5. 自動生成檔案清單
    - name: Generate File List
      run: |
        sh ./singlefile-repo/export-filename.sh 
        cd singlefile-repo
        sh ./replace-html.sh 
        rm *.sh index_sample
        cd .. 

    # 6. 構建 Jekyll 靜態網站
    - name: Build Jekyll Site
      run: |
        bundle install
        bundle exec jekyll build --source singlefile-repo --destination _site 
      
    # 7. 檢查生成的檔案
    #- name: List Directory Structure
    #  run: |
    #    echo "Origin: "
    #    git remote get-url origin
    #    echo "+++++++++++++++++++++++++++++++"
    #    echo "List Folder:  -- _site -- "
    #    ls -al _site
    #    #cat _site/index.html
    #    echo "+++++++++++++++++++++++++++++++"
    #    echo "List Folder:  -- singlefile-rep -- "
    #    ls -al singlefile-repo

    # 8. 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        
