
name: Deploy Jekyll Site from Private Repo

on:
  push:
    branches: ["main"] # 監控 main 分支的變更
    
  workflow_dispatch: # 支援手動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 檢出 Public Repository
    - name: Checkout Public Repository
      uses: actions/checkout@v3

    # 2. 檢出 Private Repository (SingleFile-Archives)
    - name: Checkout Private Repository
      uses: actions/checkout@v3
      with:
        repository: Dolphin0317/SingleFile-Archives
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Private Token
        path: singlefile-repo # 提取到此資料夾

    # 3. 創建 singlefile-repo 目錄（如果不存在），然後從 Public Repo 複製必要檔案
    - name: Copy index_sample, *.css, *.sh and *.js to singlefile-repo
      run: |
        # 確保 singlefile-repo 目錄存在，並將檔案拷貝到 singlefile-repo 目錄
        mkdir -p singlefile-repo
        cp index_sample *.css *.js *.sh singlefile-repo/
    
    #- name: Check Private Repo singlefile-repo Directory Structure
    #  run: |
    #    echo "Listing the Public Repo singlefile-repo directory structure:"
    #    ls -la singlefile-repo/

    # 4. 設置 Ruby 環境 (Jekyll 需要)
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
        
    # 5. 自動生成檔案清單
    - name: Generate File List
      run: |
        # 設定環境變數來確保使用 UTF-8 編碼
        export LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8

        sh ./singlefile-repo/export-filename.sh
        cd _singlefile-repo && sh ./replace-html.sh && cd .. 
        
    # 6. 檢查生成的檔案
    #- name: Check Generate File
    #  run: |        
    #    echo "Generated file-list.txt content:"
    #    cat singlefile-repo/file-list.txt
    #    echo "Files in singlefile-repo directory (sorted by creation date):"
    #    find singlefile-repo -type f -name "*.html" -printf "%T@ %p\n" | sort -k1,1nr

    # 7. 構建 Jekyll 靜態網站
    - name: Build Jekyll Site
      run: |
        bundle install
        bundle exec jekyll build --source singlefile-repo --destination _site 
        rm _site/index_sample _site/*.sh
        rm singlefile-repo/index_sample singlefile-repo/*.sh
        
        #echo " List _site  Folder"
        #ls -al _site/
        
        #echo " Show Index.html &&&  file-list.txt "
        #echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        #cat _site/index.html
        #cat _site/file-list.txt
        #echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

    # 8. 檢查 _site 目錄結構
    - name: Check Private Repo _site Directory Structure
      run: |
        echo "Listing the Private Repo _site directory structure:"
        ls -la _site/ 
        git remote get-url origin
    
    # 9. 清理檔案
    - name: Clean File
      run: |
        ls -al _site
        echo "====================="
        ls -al singlefile-repo

    # 10. 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        
